/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minimarketpoo;
import vista.FrmEmpleado;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JFrame {
    
    private FrmEmpleado frmEmpleado;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMantenimiento = new javax.swing.JMenu();
        mnuEmpleado = new javax.swing.JMenuItem();
        mnuCliente = new javax.swing.JMenuItem();
        mnuProveedor = new javax.swing.JMenuItem();
        mnuProducto = new javax.swing.JMenuItem();
        mnuCategoria = new javax.swing.JMenuItem();
        mnuInventario = new javax.swing.JMenuItem();
        mnuUsuario = new javax.swing.JMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        mnuVenta = new javax.swing.JMenuItem();
        mnuCompra = new javax.swing.JMenuItem();
        mnuCarritoVenta = new javax.swing.JMenuItem();
        menuControl = new javax.swing.JMenu();
        mnuAsistencia = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        menuMantenimiento.setText("Mantenimiento");

        mnuEmpleado.setText("Empleado");
        mnuEmpleado.addActionListener(this::mnuEmpleadoActionPerformed);
        menuMantenimiento.add(mnuEmpleado);

        mnuCliente.setText("Cliente");
        menuMantenimiento.add(mnuCliente);

        mnuProveedor.setText("Proveedor");
        menuMantenimiento.add(mnuProveedor);

        mnuProducto.setText("Producto");
        menuMantenimiento.add(mnuProducto);

        mnuCategoria.setText("Categoria");
        menuMantenimiento.add(mnuCategoria);

        mnuInventario.setText("Inventario");
        menuMantenimiento.add(mnuInventario);

        mnuUsuario.setText("Usuario");
        menuMantenimiento.add(mnuUsuario);

        jMenuBar1.add(menuMantenimiento);

        menuMovimientos.setText("Movimiento");

        mnuVenta.setText("Venta");
        menuMovimientos.add(mnuVenta);

        mnuCompra.setText("Compra");
        mnuCompra.addActionListener(this::mnuCompraActionPerformed);
        menuMovimientos.add(mnuCompra);

        mnuCarritoVenta.setText("Carrito venta");
        menuMovimientos.add(mnuCarritoVenta);

        jMenuBar1.add(menuMovimientos);

        menuControl.setText("Control");

        mnuAsistencia.setText("Asistencia");
        mnuAsistencia.addActionListener(this::mnuAsistenciaActionPerformed);
        menuControl.add(mnuAsistencia);

        mnuReporte.setText("Reporte");
        menuControl.add(mnuReporte);

        jMenuBar1.add(menuControl);

        menuSistema.setText("Sistema");

        mnuCerrarSesion.setText("Cerrar seción");
        menuSistema.add(mnuCerrarSesion);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(this::mnuSalirActionPerformed);
        menuSistema.add(mnuSalir);

        jMenuBar1.add(menuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpleadoActionPerformed
        // TODO add your handling code here:
        if (frmEmpleado == null || frmEmpleado.isClosed()) {
            frmEmpleado = new FrmEmpleado();
            desktopPane.add(frmEmpleado);
            frmEmpleado.setVisible(true);
        }
    }//GEN-LAST:event_mnuEmpleadoActionPerformed

    private void mnuCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCompraActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAsistenciaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuControl;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenuItem mnuAsistencia;
    private javax.swing.JMenuItem mnuCarritoVenta;
    private javax.swing.JMenuItem mnuCategoria;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuCliente;
    private javax.swing.JMenuItem mnuCompra;
    private javax.swing.JMenuItem mnuEmpleado;
    private javax.swing.JMenuItem mnuInventario;
    private javax.swing.JMenuItem mnuProducto;
    private javax.swing.JMenuItem mnuProveedor;
    private javax.swing.JMenuItem mnuReporte;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuUsuario;
    private javax.swing.JMenuItem mnuVenta;
    // End of variables declaration//GEN-END:variables
}
